In [1]:
import numpy as np

In [7]:
a1=np.array([1,2,3,4,5])
multiarray=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.zeros((4,4))
a3=np.ones((2,5))


In [15]:
print(a1)
print(multiarray)
print(a2)
print(a3)
print(a1[1:4])
print(multiarray[0:2,1:3])

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[2 3 4]
[[2 3]
 [5 6]]
